In [1]:
import os
import time
import pandas as pd
import numpy as np

from astropy.io import ascii
from astropy.coordinates import SkyCoord
from SPLASH.pipeline import Splash_Pipeline

In [13]:
import astro_prost
!pip show astro_prost

Name: astro-prost
Version: 1.2.12
Summary:
Home-page:
Author:
Author-email: Alex Gagliano <gaglian2@mit.edu>
License: MIT License

        Copyright (c) 2024 Alex Gagliano

        Permission is hereby granted, free of charge, to any person obtaining a copy
        of this software and associated documentation files (the "Software"), to deal
        in the Software without restriction, including without limitation the rights
        to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        copies of the Software, and to permit persons to whom the Software is
        furnished to do so, subject to the following conditions:

        The above copyright notice and this permission notice shall be included in all
        copies or substantial portions of the Software.

        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
        AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
        LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
        OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
        SOFTWARE.

Location: /Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages
Requires: astro-datalab, astropy, colorama, filelock, matplotlib, numpy, pandas, requests, scikit-learn, scipy, sfdmap, sfdmap2, specutils, tqdm
Required-by: astro-SPLASH

# Load in data

In [2]:
# Load in 100 bts host grizy observations
try:
    bts_hosts = ascii.read('demo_bts_hosts.ecsv')
except FileNotFoundError:
    os.chdir('SPLASH_demo')
    bts_hosts = ascii.read('demo_bts_hosts.ecsv')
bts_hosts = bts_hosts[1:]  # drop annoying row
bts_df = bts_hosts.to_pandas()
bts_df.head()

,objID_3pi,raStack_3pi,decStack_3pi,primaryDetection_3pi,gKronMag_3pi,rKronMag_3pi,iKronMag_3pi,zKronMag_3pi,yKronMag_3pi,gKronMagErr_3pi,rKronMagErr_3pi,iKronMagErr_3pi,zKronMagErr_3pi,yKronMagErr_3pi,ps_score_3pi,SN_ra,SN_dec,sn_class,sn_redshift,ZTFID
0,148231465149294617,146.514940,33.528361,1,18.2387,17.9746,17.8750,17.8532,17.7821,0.004157,0.004871,0.004281,0.014407,0.019814,0.021125,146.514792,33.528250,SN II,0.03800,ZTF18aacemcn
1,153731349546771375,134.954717,38.108970,1,18.7478,19.0585,18.6466,18.8301,18.6221,0.006392,0.009475,0.004919,0.017235,0.038667,0.017411,134.954667,38.109056,SN II,0.07247,ZTF18aacnlxz
2,169101206490177628,120.649031,50.922461,1,16.5325,15.6522,15.2551,15.0064,14.7582,0.002335,0.002128,0.000867,0.001623,0.003512,0.075905,120.648958,50.922528,SN Ia,0.05295,ZTF18aadlaxo
3,159661026075384557,102.607536,43.053266,1,NaN,14.2309,13.1660,12.9816,12.8047,NaN,0.000836,0.000408,0.001003,0.001687,0.154649,102.607542,43.053222,SN IIn,0.01885,ZTF18aadmssd
4,146001295340652041,129.534082,31.667894,1,17.2694,16.9697,16.8672,16.8232,16.7636,0.004272,0.003413,0.005182,0.005542,0.014564,0.004667,129.533958,31.667917,SN II,0.03057,ZTF18aadsuxd

In [3]:
def get_angular_separation(ra1, dec1, ra2, dec2, unit1='deg', unit2='deg'):
    """Function to calculate angular separation in arcseconds"""
    coord1 = SkyCoord(ra1, dec1, unit=unit1)
    coord2 = SkyCoord(ra2, dec2, unit=unit2)
    return coord1.separation(coord2).arcsec

def ab_mag_to_flux(AB_mag: np.ndarray) -> np.ndarray:
    """Convert AB magnitude to flux in mJy"""
    return 10**((AB_mag - 8.9) / -2.5) * 1000

ab_magerr_to_ferr = lambda sigma_m, f: np.abs(f * np.log(10) * (sigma_m / 2.5))  # transformation on the error of a magnitude turned into flux

# Add angular separation and grib data
bts_df['angular_separation_arcsec'] = get_angular_separation(bts_df['raStack_3pi'], bts_df['decStack_3pi'], bts_df['SN_ra'], bts_df['SN_dec'], unit1='deg', unit2='deg')
grizy = bts_df[['gKronMag_3pi', 'rKronMag_3pi', 'iKronMag_3pi', 'zKronMag_3pi', 'yKronMag_3pi']].to_numpy().astype(float)
grizy_err = bts_df[['gKronMagErr_3pi', 'rKronMagErr_3pi', 'iKronMagErr_3pi', 'zKronMagErr_3pi', 'yKronMagErr_3pi']].to_numpy().astype(float)
angular_seps = bts_df['angular_separation_arcsec'].to_numpy().astype(float)

# Convert the grizy data to mJy
grizy = ab_mag_to_flux(grizy)
grizy_err = ab_magerr_to_ferr(grizy_err, grizy)

grizy, angular_seps

(array([[1.83873863e-01, 2.34509262e-01, 2.57039578e-01, 2.62252719e-01,
         2.80001269e-01],
        [1.15048245e-01, 8.64171621e-02, 1.26287394e-01, 1.06649789e-01,
         1.29169506e-01],
        [8.85115610e-01, 1.99122346e+00, 2.87051619e+00, 3.60944144e+00,
         4.53649044e+00],
        [           nan, 7.37292812e+00, 1.96607463e+01, 2.33002188e+01,
         2.74233180e+01],
        [4.48993444e-01, 5.91725111e-01, 6.50309353e-01, 6.77204757e-01,
         7.15418226e-01],
        [2.98483274e-01, 6.53792599e-01, 1.09415790e+00, 1.42902557e+00,
         1.69855651e+00],
        [6.01893981e-01, 1.23720025e+00, 1.92415476e+00, 2.25029782e+00,
         2.59680895e+00],
        [1.73988282e+00,            nan,            nan,            nan,
                    nan],
        [3.22760218e+00, 5.96815371e+00, 8.96107269e+00, 1.00110585e+01,
         1.09496440e+01],
        [4.09449175e-01, 8.94046279e-01, 1.34091114e+00, 1.71316818e+00,
         2.08276370e+00],
        [2.61963027e+00, 4.78806459e+00, 6.81584962e+00, 8.17560687e+00,
         9.89281756e+00],
        [2.95447283e-01, 5.95168586e-01, 8.73775775e-01, 1.08502564e+00,
         1.33045442e+00],
        [2.03798039e-01, 2.89121241e-01, 3.80644887e-01, 4.08469844e-01,
         3.96424055e-01],
        [4.15757412e+00, 7.96819585e+00, 1.05896108e+01, 1.36094320e+01,
         1.70623953e+01],
        [6.75087396e-01, 1.32984186e+00, 1.92450924e+00, 2.22105851e+00,
         2.71468848e+00],
        [2.54167490e+00, 4.82036584e+00, 6.80142636e+00, 8.24517732e+00,
         9.50079615e+00],
        [1.25487365e+00, 1.85284888e+00, 2.42705713e+00, 2.60183649e+00,
         2.99695347e+00],
        [1.02820568e-01, 1.72329648e-01, 2.19705030e-01, 2.57134293e-01,
         2.81838293e-01],
        [3.16169520e+00, 4.64344173e+00, 5.56416500e+00, 6.18927814e+00,
         6.87384920e+00],
        [5.24710796e-01, 9.01820285e-01, 1.28422169e+00, 1.52124793e+00,
         1.83907737e+00],
        [           nan,            nan,            nan,            nan,
         8.66083969e-02],
        [6.97782382e-01, 1.18456801e+00, 1.61094235e+00, 1.83231442e+00,
         2.12970769e+00],
        [7.40627784e-01, 1.40501189e+00, 2.03011201e+00, 2.36026084e+00,
         2.93386415e+00],
        [1.88955701e-01, 2.54988151e-01, 3.35150599e-01, 3.40753245e-01,
         3.65460126e-01],
        [3.73284537e-01, 7.88787464e-01, 1.17608849e+00, 1.49885631e+00,
         1.74357246e+00],
        [4.13694741e-01, 7.47480728e-01, 1.09779184e+00, 1.26473635e+00,
         1.49032161e+00],
        [7.25370685e-01, 1.23004217e+00, 1.60176943e+00, 2.00096734e+00,
         2.44163083e+00],
        [1.69699280e+00, 3.14600928e+00, 4.29892630e+00, 5.31667361e+00,
         6.58506400e+00],
        [1.16016564e+00, 2.25673207e+00, 3.07723030e+00, 3.85798025e+00,
         4.71454733e+00],
        [1.59162224e+00, 3.01272853e+00, 4.11301222e+00, 4.91586559e+00,
         5.84574679e+00],
        [1.38203805e+01, 3.08602898e+01, 3.88221873e+01, 5.78735336e+01,
         7.35393861e+01],
        [1.13407036e+00, 2.25569304e+00, 3.42736218e+00, 4.56961909e+00,
         4.98471118e+00],
        [1.08262986e+00, 1.79192571e+00, 2.44748478e+00, 2.64801231e+00,
         3.00940058e+00],
        [7.80620586e+00, 1.47611434e+01, 2.11933690e+01, 2.71293882e+01,
         3.49526413e+01],
        [4.63745811e+00, 7.40627784e+00, 9.37993870e+00, 1.10052522e+01,
         1.32044404e+01],
        [           nan, 5.24904142e-02, 8.40620545e-02, 1.12989998e-01,
         1.05118705e-01],
        [9.25209322e-01, 1.44650520e+00, 1.91126101e+00, 2.18072047e+00,
         2.71044126e+00],
        [1.21350061e+00, 2.17090091e+00, 2.95583373e+00, 3.75629766e+00,
         4.73369203e+00],
        [1.74325131e+00, 3.22433383e+00, 4.55155715e+00, 5.56365254e+00,
         6.68467042e+00],
        [1.85182524e+00, 2.92442171e+00, 3.72014613e+00, 4.44959005e+00,
         5.33384020e+00],
        [1.50771758e+00, 3.13184313e+00, 4.52605680e+00, 5.55853059e+00,
         6.69144635e+00],
        [           nan, 2.54894227e+01, 3.74248441e+01, 3.91886227e+01,
         4.45697297e+01],
        [1.48744186e-01, 2.27111957e-01, 2.92684686e-01, 3.15994847e-01,
         3.47728270e-01],
        [1.44145139e-01, 2.69376682e-01, 3.78407730e-01, 4.34790454e-01,
         4.83459390e-01],
        [3.15151951e-01, 4.81016529e-01, 5.66604475e-01, 5.71689216e-01,
         4.37441518e-01],
        [1.49844222e+00, 2.59131375e+00, 2.71368854e+00, 4.24776028e+00,
         5.13050364e+00],
        [1.53787133e-01, 2.24698410e-01, 6.20011864e-01, 3.50299889e-01,
         4.56541225e-01],
        [2.89067988e-01, 3.58030479e-01, 5.02203806e-01, 4.69245374e-01,
         4.94766174e-01],
        [2.42526947e+00, 3.65325511e+00, 4.48538783e+00, 4.28943410e+00,
         6.25748763e+00],
        [2.51814074e-01, 5.18322426e-01, 7.13247076e-01, 7.92939404e-01,
         9.43018038e-01],
        [1.47407642e-01, 2.54729944e-01, 3.55042220e-01, 4.12173437e-01,
         4.74110965e-01],
        [1.59001053e+00, 2.47787846e+00, 3.26317226e+00, 3.59848751e+00,
         4.26500947e+00],
        [3.11975148e-01, 5.62082417e-01, 7.87045790e-01, 9.09410575e-01,
         1.03580976e+00],
        [3.27642326e-01, 5.75280959e-01, 7.88279078e-01, 9.07318989e-01,
         9.74989638e-01],
        [4.53231410e-02, 5.98356482e-02, 7.55648805e-02, 5.92706923e-02,
         6.10210955e-02],
        [6.56447502e-01, 1.51635190e+00, 2.34682119e+00, 2.84786895e+00,
         3.87328987e+00],
        [1.32007924e+00, 3.23712895e+00, 4.97141479e+00, 6.05954479e+00,
         8.01308962e+00],
        [2.28412570e+00, 4.17176657e+00, 5.57185749e+00, 6.69822914e+00,
         8.30080095e+00],
        [1.71301040e+00, 3.35058006e+00, 4.60595828e+00, 5.57904674e+00,
         6.70810729e+00],
        [4.80042844e-01, 1.01784114e+00, 1.47475542e+00, 1.77647868e+00,
         2.15496390e+00],
        [4.95222080e-01, 1.00175150e+00, 1.43403582e+00, 1.66555892e+00,
         1.70938544e+00],
        [7.60466347e-01, 1.21719455e+00, 1.67633186e+00, 1.90458342e+00,
         2.36809979e+00],
        [8.96107269e-02, 1.18850223e-01, 1.54425850e-01, 1.62390269e-01,
         1.39521135e-01],
        [9.86370330e-01, 1.30568977e+00, 1.46973826e+00, 1.60088450e+00,
         1.61644153e+00],
        [1.42429516e+00, 2.32937816e+00, 3.20302258e+00, 3.93622577e+00,
         4.68209261e+00],
        [5.82961669e-01, 8.51843865e-01, 1.01952998e+00, 1.01437842e+00,
         1.19146146e+00],
        [4.49821283e-02, 8.94622878e-02, 1.27092523e-01, 1.49128277e-01,
                    nan],
        [2.15635371e+00, 3.92500306e+00, 5.51010659e+00, 6.52709600e+00,
         7.71898150e+00],
        [3.18771877e+00, 4.45779405e+00, 6.51268390e+00, 7.07750199e+00,
         9.20958372e+00],
        [9.04148987e-01, 1.11562953e+00, 1.39598258e+00, 1.31534597e+00,
         1.37214498e+00],
        [7.07033514e-01, 1.18402262e+00, 1.60501834e+00, 1.75824747e+00,
         1.95236044e+00],
        [1.31995766e+00, 2.18433880e+00, 2.89947922e+00, 3.22136548e+00,
         3.89941987e+00],
        [4.52605680e-01, 7.50446955e-01, 8.80562122e-01, 9.59754153e-01,
         1.13208751e+00],
        [2.23563037e+00, 3.27009222e+00, 3.88186118e+00, 4.53858005e+00,
         5.11823238e+00],
        [3.23176669e+00, 6.07575146e+00, 8.37529282e+00, 9.82109699e+00,
         1.19563880e+01],
        [           nan, 2.88881679e-01,            nan, 3.50978085e-01,
         1.20970646e-01],
        [2.09064358e-01, 3.43494668e-01, 4.67476733e-01, 4.96363685e-01,
         5.62496727e-01],
        [5.58521634e-01, 9.00077696e-01, 1.29014939e+00, 1.45144305e+00,
         1.71143339e+00],
        [3.24130575e-01, 4.29536427e-01, 5.08768249e-01, 5.88409939e-01,
         4.89778819e-01],
        [2.85574878e-01, 6.17788756e-01, 8.78698733e-01, 1.13689407e+00,
         1.27197917e+00],
        [4.49489965e-01, 7.11344536e-01, 9.51305483e-01, 9.52094376e-01,
         1.09748856e+00],
        [7.16473282e-01, 1.11758355e+00, 1.52307048e+00, 1.73508198e+00,
         1.86140124e+00],
        [2.36308857e+00, 4.78057350e+00, 7.20244582e+00, 9.18924858e+00,
         1.11224382e+01],
        [           nan,            nan, 7.75818265e-01,            nan,
                    nan],
        [3.28306892e-01, 5.50756967e-01, 7.07424343e-01, 7.65949258e-01,
         9.40502599e-01],
        [9.31622567e-01, 2.19361294e+00, 3.24339617e+00, 4.50069932e+00,
         5.66708857e+00],
        [6.18301073e-01, 9.72388916e-01, 1.35918947e+00, 1.52152818e+00,
         1.45465499e+00],
        [2.68583915e+00, 5.38418533e+00, 7.81771799e+00, 9.42844344e+00,
         1.17176359e+01],
        [9.84011106e-01, 2.02656249e+00, 3.15122926e+00, 4.05994360e+00,
         4.77265454e+00],
        [2.11018242e+00, 4.34750410e+00, 6.68220815e+00, 8.89201118e+00,
         1.00581938e+01],
        [9.96506188e-01, 1.90791929e+00, 2.66097013e+00, 3.16577467e+00,
         4.12325316e+00],
        [7.65032702e-01, 1.23117560e+00, 1.57615890e+00, 1.77566077e+00,
         2.13225922e+00],
        [1.24188105e+00, 2.73905025e+00, 4.05657958e+00, 5.05638344e+00,
         5.85167234e+00],
        [2.69724254e+00, 5.85652498e+00, 9.22401499e+00, 1.17036143e+01,
         1.59676131e+01],
        [1.90704087e+00, 3.19241983e+00, 5.02990752e+00, 6.15290203e+00,
         7.74961273e+00],
        [1.52826969e-01, 2.19624103e-01, 2.63172193e-01, 2.76312161e-01,
         3.14571954e-01],
        [4.99206234e-01, 6.95216386e-01, 8.35218297e-01, 8.07755642e-01,
         7.35258409e-01],
        [6.41800424e+00, 1.21204850e+01, 1.71996655e+01, 2.09045104e+01,
         2.28328435e+01],
        [3.71329968e+00, 7.22636677e+00, 1.03609601e+01, 1.26928749e+01,
         1.63862660e+01]]),
 array([ 0.59790783,  0.33839217,  0.29304473,  0.15764768,  0.38873667,
         1.19332497,  0.22112834,  2.39513878,  0.55214775,  0.61530609,
         1.56152809,  0.23644125,  0.26814286,  0.38758386,  1.13034269,
         1.82079545,  1.35356101,  0.38554596,  0.50651915,  1.28880933,
         2.63569943,  1.8956027 ,  0.52685127,  0.73257432, 12.91170999,
         0.54786141,  0.21660255,  0.65362532,  0.56208815,  0.69764556,
         0.40538941,  1.20329093,  0.7154132 ,  1.20064417,  0.27345569,
         6.59457381,  0.7506793 ,  0.82832946,  0.83542265,  2.9099935 ,
         1.76131243, 11.41086437,  1.46817047,  1.32578146,  7.30207794,
         0.58130978,  0.12725298,  0.53075436, 23.09659572,  0.05202068,
         0.05541568,  1.12583887,  0.30059171,  0.26390679,  2.73031495,
         2.66906267,  1.03118848,  1.39827337,  0.87561215,  0.33057319,
         0.16996934,  1.18635801,  0.65885774,  5.63958197,  2.32019234,
         0.4657513 ,  4.7506407 ,  2.64762205,  0.52068592,  1.72275293,
         1.49020733,  5.68872144,  0.42592662,  3.64610104,  9.73422128,
         6.27497055,  1.07530953,  0.48695391,  5.66503084,  0.30095132,
         2.33654543,  0.47362687,  0.24446317,  1.58027626,  0.92864488,
         0.94518791,  1.28982048,  2.93057316,  0.26213411,  0.28707108,
         1.54781179,  1.25966473,  0.28278739, 13.64442919,  4.798285  ,
         0.76518453,  1.03714677,  8.28312778, 14.65486634]))

In [4]:
nan_mask = ~(np.sum(np.isnan(grizy), axis=1)==0)

# Use the SPLASH pipeline

In [5]:
# Load pipeline object
pipeline = Splash_Pipeline(
    pre_transformed=False,      # whether the given data is pre-logged and nnormalized
    within_4sigma=True,         # whether we only want to classify objects with properties within 4-sigma of the training set
    nan_thresh_ratio=1.0,       # to keep this notebook concise, we are allowing the pipeline to imput any num of nans
)

In [6]:
# Predict the classes. n_resamples is the number of boostraps for getting the median predicted host properties.
start_time = time.time()
classes_only_phot = pipeline.infer_classes(grizy=grizy, redshift=np.array(bts_hosts['sn_redshift'].filled(np.nan)), angular_sep=angular_seps, grizy_err=grizy_err, n_resamples=50)
duration = time.time() - start_time
print(f'{grizy.shape[0]} classifications produced in {duration} seconds (~{duration / grizy.shape[0]} seconds per classificaiton).')

99 classifications produced in 0.09507107734680176 seconds (~0.0009603139125939572 seconds per classificaiton).

In [7]:
print(f'Number of each class:\n{pd.Series(classes_only_phot).value_counts()}\n\nThe class labels are\n0=Ia\n1=Ib/c\n2=SLSN\n3=IIn\n4=II (P/L)\n-1=Outside train properties 4 sigma\n-2=No host found')

Number of each class:
0    92
4     7
Name: count, dtype: int64

The class labels are
0=Ia
1=Ib/c
2=SLSN
3=IIn
4=II (P/L)
-1=Outside train properties 4 sigma
-2=No host found

In [8]:
# We can also take a look at the predicted host properties of each supernova
props, props_err = pipeline.infer_host_properties(
    grizy=grizy, redshift=np.array(bts_hosts['sn_redshift'].filled(np.nan)), grizy_err=grizy_err, n_resamples=50, return_normalized=False
)  # return_normalized will return the properties normalized with the train mean and std
props, props_err  # in order (log(mass), log(sfr), redshift)

(array([[ 8.96030474e+00, -1.09284876e+00],
        [ 8.86660804e+00, -5.37448039e-01],
        [ 1.07131061e+01, -1.27656469e+00],
        [ 1.05151734e+01,  2.99547517e-01],
        [ 9.19497656e+00, -8.82698422e-01],
        [ 1.03862756e+01, -1.03665597e+00],
        [ 1.03944637e+01, -9.68966905e-01],
        [ 1.05663692e+01, -5.56251249e-02],
        [ 1.02992324e+01, -2.18445250e-01],
        [ 1.04928076e+01, -1.15004314e+00],
        [ 1.08764599e+01, -1.08227383e-01],
        [ 1.02998103e+01, -9.10195161e-01],
        [ 9.78862361e+00, -3.51083124e-01],
        [ 1.09631863e+01, -1.22674035e-01],
        [ 1.04394108e+01, -9.93962244e-01],
        [ 9.86848474e+00, -2.79566896e-01],
        [ 1.03347036e+01,  7.55876043e-02],
        [ 9.76961174e+00, -8.67952162e-01],
        [ 1.02123146e+01,  2.83352396e-02],
        [ 1.04002912e+01, -2.00662565e-01],
        [ 8.73715062e+00, -1.29268491e+00],
        [ 1.04775170e+01, -4.65414969e-01],
        [ 1.08330441e+01, -7.90327273e-01],
        [ 9.70003441e+00, -4.30415407e-01],
        [ 1.04198721e+01, -1.07354760e+00],
        [ 1.03206040e+01, -5.85198763e-01],
        [ 9.47039483e+00, -6.36059334e-01],
        [ 1.06368045e+01, -2.52770294e-01],
        [ 1.01750497e+01, -4.73678563e-01],
        [ 1.10560132e+01, -6.56355883e-01],
        [ 1.09223989e+01, -3.13541932e-02],
        [ 1.08922781e+01, -1.40226775e-01],
        [ 1.06654537e+01, -4.95455093e-01],
        [ 1.10642727e+01,  3.98122151e-01],
        [ 1.05009601e+01,  2.86819412e-01],
        [ 9.22256110e+00, -1.93877880e+00],
        [ 1.04010720e+01,  4.01896937e-02],
        [ 1.07536887e+01, -2.81520159e-02],
        [ 1.07289312e+01, -2.07349630e-01],
        [ 1.00924108e+01, -7.90394957e-02],
        [ 1.09572164e+01, -8.37436304e-01],
        [ 1.10683006e+01, -1.89691027e+00],
        [ 9.65368082e+00, -6.26385184e-01],
        [ 9.78734845e+00, -1.24810279e+00],
        [ 9.56419291e+00, -5.92700446e-01],
        [ 1.04455693e+01,  2.37216594e-01],
        [ 8.88886107e+00, -1.15682709e+00],
        [ 9.64988842e+00, -4.75321507e-01],
        [ 9.99685864e+00, -5.32627743e-01],
        [ 1.02904247e+01, -1.26071258e+00],
        [ 9.73712571e+00, -6.62014827e-01],
        [ 1.04807306e+01, -1.37972906e-02],
        [ 1.02812666e+01, -8.12726759e-01],
        [ 1.00374504e+01, -7.19267072e-01],
        [ 8.97548106e+00, -1.07925826e+00],
        [ 1.06109115e+01, -1.39589877e+00],
        [ 1.11245841e+01, -1.64262801e+00],
        [ 1.07242534e+01, -3.36006410e-01],
        [ 1.03684208e+01, -5.96165795e-01],
        [ 1.04213476e+01, -1.27799757e+00],
        [ 1.04121062e+01, -1.35677126e+00],
        [ 1.02159705e+01,  1.81928049e-02],
        [ 9.45178747e+00, -6.52722365e-01],
        [ 9.11556982e+00, -9.53807742e-01],
        [ 1.02592332e+01,  7.03511716e-02],
        [ 9.28689080e+00, -8.00388547e-01],
        [ 9.95735617e+00, -1.29911067e+00],
        [ 1.02420654e+01, -1.37261370e-01],
        [ 1.04380563e+01,  2.30488584e-01],
        [ 9.63391376e+00, -4.89626932e-01],
        [ 1.06103019e+01, -6.42591728e-01],
        [ 1.03638341e+01, -3.08713588e-01],
        [ 9.46124477e+00, -9.94080121e-01],
        [ 1.00121670e+01, -1.50898362e-01],
        [ 1.06644087e+01, -4.10107263e-01],
        [ 8.97248970e+00, -1.22117651e+00],
        [ 9.93432601e+00, -8.87941074e-01],
        [ 1.04111728e+01, -7.94210174e-02],
        [ 8.93185695e+00, -1.11832396e+00],
        [ 1.07956684e+01, -1.49489784e+00],
        [ 1.01098225e+01, -8.65725979e-01],
        [ 1.01943098e+01,  1.22118396e-02],
        [ 1.09111595e+01, -1.86119886e-01],
        [ 9.97785296e+00, -1.24870966e+00],
        [ 9.28012243e+00, -8.06449670e-01],
        [ 1.02568242e+01, -7.93579537e-01],
        [ 1.05314228e+01, -1.29541909e-01],
        [ 1.08450994e+01, -5.18565211e-01],
        [ 9.23833606e+00, -8.43869674e-01],
        [ 1.03260263e+01,  7.25186892e-02],
        [ 1.02410350e+01, -6.20104879e-01],
        [ 9.50904638e+00, -6.01446587e-01],
        [ 1.09577922e+01, -1.08388300e+00],
        [ 1.11618800e+01, -4.14767231e-01],
        [ 1.05459725e+01,  3.27128358e-01],
        [ 9.82022497e+00, -7.10312924e-01],
        [ 9.98242691e+00, -6.76729289e-01],
        [ 1.07567422e+01,  8.65090131e-03],
        [ 1.08223793e+01, -1.96631079e-01]]),
 array([[9.26253307e-16, 9.24507519e-16],
        [5.55751984e-16, 1.15563440e-16],
        [4.63126654e-16, 9.30267747e-16],
        [4.67551531e-16, 1.76399935e-16],
        [5.55751984e-16, 2.31126880e-16],
        [3.71484163e-16, 1.40588992e-16],
        [1.38937996e-16, 2.31126880e-16],
        [2.77875992e-16, 4.33362900e-17],
        [1.38937996e-16, 5.77817200e-17],
        [5.55751984e-16, 9.24507519e-16],
        [5.55751984e-16, 0.00000000e+00],
        [2.77875992e-16, 4.62253760e-16],
        [4.63126654e-17, 5.77817200e-17],
        [7.41002646e-16, 1.08340725e-17],
        [2.74771135e-16, 1.38676128e-16],
        [9.26253307e-17, 8.66725799e-17],
        [9.26253307e-17, 2.88908600e-17],
        [0.00000000e+00, 3.46690320e-16],
        [0.00000000e+00, 2.02236020e-16],
        [3.24188658e-16, 5.05590050e-17],
        [3.70501323e-16, 0.00000000e+00],
        [9.26253307e-17, 4.55267155e-16],
        [4.63126654e-16, 4.62253760e-16],
        [1.85250661e-16, 1.73345160e-16],
        [2.77875992e-16, 1.15563440e-16],
        [4.16813988e-16, 1.73345160e-16],
        [3.70501323e-16, 1.73345160e-16],
        [0.00000000e+00, 5.77817200e-17],
        [0.00000000e+00, 2.31126880e-16],
        [0.00000000e+00, 2.31126880e-16],
        [5.55751984e-16, 7.22271500e-17],
        [0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.15563440e-16],
        [0.00000000e+00, 4.62253760e-16],
        [2.77875992e-16, 1.73345160e-16],
        [7.41002646e-16, 9.24507519e-16],
        [4.28986297e-16, 3.00242624e-17],
        [3.70501323e-16, 5.77817200e-17],
        [1.85250661e-16, 4.33362900e-17],
        [1.04203497e-16, 1.44454300e-17],
        [9.26253307e-16, 3.46690320e-16],
        [0.00000000e+00, 2.31126880e-16],
        [9.26253307e-17, 4.04472040e-16],
        [2.31563327e-16, 0.00000000e+00],
        [3.70501323e-16, 1.73345160e-16],
        [2.75394907e-16, 2.87053630e-16],
        [1.29675463e-15, 6.93380640e-16],
        [2.77875992e-16, 2.88908600e-16],
        [2.77875992e-17, 2.02153458e-16],
        [9.26253307e-17, 6.93380640e-16],
        [0.00000000e+00, 2.31126880e-16],
        [6.48377315e-16, 4.33362900e-17],
        [3.70501323e-16, 4.62253760e-16],
        [2.89454159e-17, 4.62253760e-16],
        [5.55751984e-16, 9.24507519e-16],
        [6.48377315e-16, 9.24507519e-16],
        [1.29675463e-15, 0.00000000e+00],
        [4.63126654e-16, 2.88908600e-17],
        [1.38937996e-16, 4.40507460e-16],
        [4.63126654e-16, 2.63525188e-16],
        [5.09439319e-16, 4.62253760e-16],
        [1.25129931e-16, 9.33492255e-17],
        [2.77875992e-16, 5.77817200e-17],
        [9.26253307e-16, 5.77817200e-16],
        [1.89372936e-16, 9.57329936e-17],
        [2.89963150e-16, 5.90618501e-16],
        [2.89454159e-17, 9.24507519e-16],
        [9.26253307e-17, 0.00000000e+00],
        [2.77875992e-16, 1.73345160e-16],
        [1.38937996e-16, 1.15563440e-16],
        [2.77875992e-16, 6.35598920e-16],
        [2.77875992e-16, 1.44454300e-16],
        [3.70501323e-16, 1.04007096e-15],
        [1.73672495e-17, 1.62511087e-17],
        [1.85250661e-16, 0.00000000e+00],
        [9.93123250e-16, 7.67257697e-16],
        [4.63126654e-17, 3.46690320e-16],
        [3.24188658e-16, 2.16681450e-17],
        [0.00000000e+00, 4.62253760e-16],
        [7.41002646e-16, 6.93380640e-16],
        [6.94689981e-17, 1.15563440e-16],
        [2.31563327e-17, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 1.15563440e-15],
        [9.26253307e-17, 8.08944080e-16],
        [1.38937996e-16, 0.00000000e+00],
        [4.63126654e-16, 0.00000000e+00],
        [1.11150397e-15, 1.15563440e-16],
        [2.32118414e-16, 2.89601150e-16],
        [9.26253307e-17, 2.60017740e-16],
        [0.00000000e+00, 3.46690320e-16],
        [3.70501323e-16, 1.15563440e-16],
        [5.55751984e-16, 5.77817200e-16],
        [0.00000000e+00, 2.88908600e-16],
        [2.77875992e-16, 4.04472040e-16],
        [6.94689981e-17, 4.62253760e-16],
        [2.02617911e-17, 5.77817200e-16],
        [4.63126654e-16, 8.66725799e-17],
        [1.01887864e-15, 2.16681450e-17]]))

# Classification from just transient coordinates

In [9]:
# Load pipeline object
pipeline = Splash_Pipeline(
    pre_transformed=False,      # whether the given data is pre-logged and nnormalized
    within_4sigma=True,         # whether we only want to classify objects with properties within 4-sigma of the training set
    nan_thresh_ratio=1.0,       # to keep this notebook concise, we are allowing the pipeline to imput any num of nans
)

In [10]:
classes = pipeline.infer_classes(
    ra=bts_hosts['SN_ra'][:25],
    dec=bts_hosts['SN_dec'][:25],
    redshift=np.array(bts_hosts['sn_redshift'].filled(np.nan))[:25],
    n_resamples=50,
)
print(f'Number of each class:\n{pd.Series(classes).value_counts()}\n\nThe class labels are 0=Ia 1=Ib/c 2=SLSN 3=IIn 4=II (P/L) -1=Outside train properties 4 sigma -2=No host found.')

Associating the catalog!

2026-03-23 11:43:30,705- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:31,045- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:31,669- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:31,912- WARNING - Association failed. Host is likely missing from the catalog.
2026-03-23 11:43:32,245- ERROR - Error processing event 2: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>
Traceback (most recent call last):
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 788, in safe_associate_transient
    return associate_transient(*args, **kwargs)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 439, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 945, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 864, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 2594, in build_decals_candidates
    candidate_hosts = fetch_decals_sources(transient_pos, search_rad, cat_cols, calc_host_props, release)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 448, in fetch_decals_sources
    result = qC.query(
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/Util.py", line 84, in __call__
    return function(*args, **kw)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 565, in query
    return qc_client._query (token=def_token(token), adql=adql, sql=sql,
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 2092, in _query
    raise queryClientError (r.text)
dl.queryClient.queryClientError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>

2026-03-23 11:43:32,321- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:32,617- ERROR - Error processing event 3: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>
Traceback (most recent call last):
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 788, in safe_associate_transient
    return associate_transient(*args, **kwargs)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 439, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 945, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 864, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 2594, in build_decals_candidates
    candidate_hosts = fetch_decals_sources(transient_pos, search_rad, cat_cols, calc_host_props, release)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 448, in fetch_decals_sources
    result = qC.query(
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/Util.py", line 84, in __call__
    return function(*args, **kw)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 565, in query
    return qc_client._query (token=def_token(token), adql=adql, sql=sql,
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 2092, in _query
    raise queryClientError (r.text)
dl.queryClient.queryClientError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>

2026-03-23 11:43:32,888- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:33,508- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:33,901- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:33,991- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:34,288- ERROR - Error processing event 6: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>
Traceback (most recent call last):
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 788, in safe_associate_transient
    return associate_transient(*args, **kwargs)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 439, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 945, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 864, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 2594, in build_decals_candidates
    candidate_hosts = fetch_decals_sources(transient_pos, search_rad, cat_cols, calc_host_props, release)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 448, in fetch_decals_sources
    result = qC.query(
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/Util.py", line 84, in __call__
    return function(*args, **kw)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 565, in query
    return qc_client._query (token=def_token(token), adql=adql, sql=sql,
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 2092, in _query
    raise queryClientError (r.text)
dl.queryClient.queryClientError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>

2026-03-23 11:43:34,428- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:34,635- WARNING - Association failed. Host is likely missing from the catalog.
2026-03-23 11:43:34,848- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:35,002- ERROR - Error processing event 7: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>
Traceback (most recent call last):
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 788, in safe_associate_transient
    return associate_transient(*args, **kwargs)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 439, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 945, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 864, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 2594, in build_decals_candidates
    candidate_hosts = fetch_decals_sources(transient_pos, search_rad, cat_cols, calc_host_props, release)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 448, in fetch_decals_sources
    result = qC.query(
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/Util.py", line 84, in __call__
    return function(*args, **kw)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 565, in query
    return qc_client._query (token=def_token(token), adql=adql, sql=sql,
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 2092, in _query
    raise queryClientError (r.text)
dl.queryClient.queryClientError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>

2026-03-23 11:43:37,715- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:38,279- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:38,552- ERROR - Error processing event 3: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>
Traceback (most recent call last):
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 788, in safe_associate_transient
    return associate_transient(*args, **kwargs)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 439, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 945, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 864, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 2594, in build_decals_candidates
    candidate_hosts = fetch_decals_sources(transient_pos, search_rad, cat_cols, calc_host_props, release)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 448, in fetch_decals_sources
    result = qC.query(
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/Util.py", line 84, in __call__
    return function(*args, **kw)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 565, in query
    return qc_client._query (token=def_token(token), adql=adql, sql=sql,
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 2092, in _query
    raise queryClientError (r.text)
dl.queryClient.queryClientError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>

2026-03-23 11:43:38,701- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:38,961- ERROR - Error processing event 6: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>
Traceback (most recent call last):
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 788, in safe_associate_transient
    return associate_transient(*args, **kwargs)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 439, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 945, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 864, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 2594, in build_decals_candidates
    candidate_hosts = fetch_decals_sources(transient_pos, search_rad, cat_cols, calc_host_props, release)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 448, in fetch_decals_sources
    result = qC.query(
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/Util.py", line 84, in __call__
    return function(*args, **kw)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 565, in query
    return qc_client._query (token=def_token(token), adql=adql, sql=sql,
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 2092, in _query
    raise queryClientError (r.text)
dl.queryClient.queryClientError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>

2026-03-23 11:43:39,110- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:39,315- WARNING - Association failed. Host is likely missing from the catalog.
2026-03-23 11:43:39,575- ERROR - Error processing event 7: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>
Traceback (most recent call last):
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 788, in safe_associate_transient
    return associate_transient(*args, **kwargs)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 439, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 945, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 864, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 2594, in build_decals_candidates
    candidate_hosts = fetch_decals_sources(transient_pos, search_rad, cat_cols, calc_host_props, release)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 448, in fetch_decals_sources
    result = qC.query(
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/Util.py", line 84, in __call__
    return function(*args, **kw)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 565, in query
    return qc_client._query (token=def_token(token), adql=adql, sql=sql,
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/dl/queryClient.py", line 2092, in _query
    raise queryClientError (r.text)
dl.queryClient.queryClientError: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>

2026-03-23 11:43:42,044- WARNING - panstarrs does not support conditioning on absmag, redshift; falling back to 'offset' only for this subset.
2026-03-23 11:43:42,341- ERROR - Error processing event 3: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.28.0</center>
</body>
</html>
Traceback (most recent call last):
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 788, in safe_associate_transient
    return associate_transient(*args, **kwargs)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/associate.py", line 439, in associate_transient
    cat.get_candidates(transient, time_query=True, logger=logger, cosmo=cosmo, calc_host_props=calc_host_props_cat, cat_cols=cat_cols)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 945, in get_candidates
    self.galaxies, self.cat_col_fields = fetch_catalog_data(self, transient, search_rad, cosmo, logger, cat_cols, calc_host_props)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 864, in fetch_catalog_data
    return catalog_func(**init_params)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 2594, in build_decals_candidates
    candidate_hosts = fetch_decals_sources(transient_pos, search_rad, cat_cols, calc_host_props, release)
  File "/Users/adamboesky/opt/anaconda3/envs/ay98_test/lib/python3.9/site-packages/astro_prost/helpers.py", line 448, in fetch_decals_sources
    result = qC.query(

Number of each class:
 0    18
-2     7
Name: count, dtype: int64

The class labels are 0=Ia 1=Ib/c 2=SLSN 3=IIn 4=II (P/L) -1=Outside train properties 4 sigma -2=No host found.

In [11]:
pipeline.transient_catalog[['best_cat'] + [k for k in pipeline.transient_catalog.keys() if 'host' in k]]

,best_cat,host_objID,host_name,host_total_posterior,host_ra,host_dec,host_redshift_mean,host_redshift_std,host_redshift_info,host_redshift_posterior,...,host_2_redshift_info,host_2_redshift_posterior,host_2_absmag_mean,host_2_absmag_std,host_2_absmag_info,host_2_absmag_posterior,host_2_offset_mean,host_2_offset_std,host_2_offset_info,host_2_offset_posterior
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,glade,2188997.0,SDSSJ085949.12+38063,0.522398,134.955000,38.108920,0.072308,0.021692,PHOT,99362.521459,...,PHOT,883.324188,-21.940004,0.9485,B,7.929658,252.893418,0.099565,,0.000000
2,glade,1060433.0,2385018,0.965070,120.649139,50.922501,0.053335,0.016000,SPEC,11072.606988,...,PHOT,770.328114,-19.640000,0.9585,B,0.085363,214.444708,0.097655,,0.000000
3,glade,1027259.0,UGC03554,0.994084,102.607574,43.053371,0.018141,0.005442,SPEC,6709.927929,...,SPEC,6709.927929,-20.732025,0.6875,B,0.051900,0.548812,0.101916,,10.075182
4,glade,2174757.0,SDSSJ083808.16+31400,0.896536,129.534000,31.667870,0.031472,0.009442,PHOT,65743.945291,...,PHOT,65743.945291,-18.649993,0.8525,B,0.089840,0.234006,0.082877,,92.226355
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,glade,1035402.0,21598,0.986521,115.494247,23.176296,0.043268,0.012980,SPEC,4681.804241,...,PHOT,68.000385,-20.849999,0.9250,B,0.092075,188.276542,0.096430,,0.000000
8,glade,1039273.0,PGC029733,0.983496,153.178818,39.373905,0.021596,0.006479,SPEC,15805.296930,...,PHOT,268.644353,-19.689998,0.9030,B,0.051210,236.443558,0.075335,,0.000000
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,glade,1038640.0,22992,0.987367,123.023956,29.404448,0.048584,0.014575,SPEC,4235.923840,...,PHOT,27.017152,-21.599994,0.9320,B,0.188586,168.147024,0.102441,,0.000000
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,glade,2527043.0,1888155,0.852290,230.519000,30.048790,0.077553,0.023266,PHOT,28405.249453,...,PHOT,28405.249453,-19.129997,0.9300,B,0.200405,0.214878,0.086143,,162.619084
13,glade,1034101.0,30689,0.988475,156.678589,21.724142,0.041378,0.012413,SPEC,4895.757431,...,PHOT,4973.280642,-19.330003,0.8475,B,0.023998,213.989471,0.099411,,0.000000
14,glade,1072508.0,2289241,0.898386,169.204880,46.910572,0.053335,0.016000,SPEC,25826.117023,...,PHOT,3663.611093,-19.790000,0.9285,B,0.248082,119.987144,0.097953,,0.000000
15,glade,1070685.0,UGC08325,0.952377,198.722549,27.008171,0.015321,0.004596,SPEC,65248.700451,...,SPEC,65248.700451,-19.050481,0.7530,B,0.084993,1.737018,0.099424,,37.846186
16,glade,1077792.0,36641,0.942081,176.357315,55.527187,0.053335,0.016000,SPEC,14088.647954,...,SPEC,9323.947346,-19.780001,0.8785,B,0.135549,214.289910,0.085117,,0.000000
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,glade,7850.0,56507,0.986127,239.497910,40.033848,0.031757,0.009527,PHOT,7345.704852,...,PHOT,7345.704852,-20.570005,0.7575,B,0.084033,0.268813,0.093813,,18.315505
19,glade,1080813.0,2362875,0.828857,219.697800,50.103230,0.068598,0.020579,SPEC,27994.447045,...,PHOT,28147.729627,-19.890002,0.8775,B,0.318366,139.866069,0.070156,,0.000000
20,glade,1048384.0,37551,0.912238,179.196518,52.484230,0.051933,0.015580,SPEC,30963.622771,...,PHOT,908.274079,-20.239999,0.9525,B,0.406933,229.379539,0.082108,,0.000000
21,glade,1058467.0,1874975,0.942410,174.020447,29.698782,0.067998,0.020399,SPEC,14103.949813,...,PHOT,13916.944777,-20.250000,0.8605,B,0.254512,273.736721,0.099446,,0.000000
22,glade,1142053.0,1861660,0.966724,180.291550,29.289141,0.079961,0.023988,SPEC,6923.407805,...,PHOT,7069.830765,-19.570001,0.8985,B,0.073580,218.024466,0.098975,,0.000000
23,glade,2417957.0,SDSSJ131806.63+27522,0.578224,199.528000,27.873250,0.074560,0.022368,PHOT,65919.592031,...,PHOT,244.682480,-19.690000,1.0960,B,0.785903,121.988907,0.094161,,0.000000
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN